// flow-typed signature: 51b7eddd5d9fe155ebc342b920079780
// flow-typed version: <<STUB>>/rotating-file-stream_v^1.2.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rotating-file-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rotating-file-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rotating-file-stream/compress' {
  declare module.exports: any;
}

declare module 'rotating-file-stream/interval' {
  declare module.exports: any;
}

declare module 'rotating-file-stream/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rotating-file-stream/compress.js' {
  declare module.exports: $Exports<'rotating-file-stream/compress'>;
}
declare module 'rotating-file-stream/index' {
  declare module.exports: $Exports<'rotating-file-stream'>;
}
declare module 'rotating-file-stream/index.js' {
  declare module.exports: $Exports<'rotating-file-stream'>;
}
declare module 'rotating-file-stream/interval.js' {
  declare module.exports: $Exports<'rotating-file-stream/interval'>;
}
declare module 'rotating-file-stream/utils.js' {
  declare module.exports: $Exports<'rotating-file-stream/utils'>;
}
